export enum HttpStatusCode {
  OK = 200,
  Created = 201,
  Accepted = 202,
  NoContent = 204,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  Conflict=409,
  InternalServerError = 500,
  NotImplemented = 501,
  ServiceUnavailable = 503,
}
export enum ApiMessage {
  generalSuccess = "Operation successfully.",
  generalError = "Operation Failed.",
  Created = "Resource successfully created.",
  badCredentials = "Invalid credentials",
  NoContent = "No content available.",
  BadRequest = "Bad request. Please check your input.",
  Unauthorized = "Unauthorized. Please login.",
  Forbidden = "Forbidden. You don't have permission to access this.",
  NotFound = "Resource not found.",
  MethodNotAllowed = "HTTP method not allowed.",
  InternalServerError = "An unexpected error occurred. Please try again later.",
  ServiceUnavailable = "Service is currently unavailable. Please try again later.",
}
